---
abstract: 'Country names in English, and subcountry names in native scripts'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Country-SubCountry
provides:
  Locale::Country::SubCountry:
    file: lib/Locale/Country/SubCountry.pm
    version: 1.03
  Locale::Country::SubCountry::Base:
    file: lib/Locale/Country/SubCountry/Base.pm
    version: 1.03
  Locale::Country::SubCountry::Database::Export:
    file: lib/Locale/Country/SubCountry/Database/Export.pm
    version: 1.03
  Locale::Country::SubCountry::Util::Config:
    file: lib/Locale/Country/SubCountry/Util/Config.pm
    version: 1.03
requires:
  Config::Tiny: 2.13
  Data::Section::Simple: 0.02
  File::Copy: 2.18
  File::HomeDir: 0.97
  Getopt::Long: 2.38
  Hash::FieldHash: 0.1
  Path::Class: 0.23
  Pod::Usage: 1.36
  Test::More: 0.98
  Text::CSV_XS: 0.8
  Text::Xslate: 1.0007
  parent: 0.224
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.03
